services:
  fahrrad-app:
    image: 'fahrrad-app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fahrrad-app
    depends_on:
      - fahrrad-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fahrrad-db:5432/fahrrad
      - SPRING_DATASOURCE_USERNAME=sample-user
      - SPRING_DATASOURCE_PASSWORD=sample-password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'

  fahrrad-db:
    image: postgres:15-alpine
    container_name: fahrrad-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fahrrad
      - POSTGRES_USER=sample-user
      - POSTGRES_PASSWORD=sample-password
    ports:
      - '5432:5432'
