services:
  fahrrad-app-test:
    image: 'fahrrad-app-test:latest'
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: fahrrad-app-test
    depends_on:
      - fahrrad-db-test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fahrrad-db-test:5432/fahrrad-test
      - SPRING_DATASOURCE_USERNAME=sample-user
      - SPRING_DATASOURCE_PASSWORD=sample-password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8081:8080'
    restart: "no"
    volumes:
      - ./src/:/app/src/

  fahrrad-db-test:
    image: postgres:15-alpine
    container_name: fahrrad-db-test
    environment:
      - POSTGRES_DB=fahrrad-test
      - POSTGRES_USER=sample-user
      - POSTGRES_PASSWORD=sample-password
    ports:
      - '5433:5432'
    restart: "no"
    stop_grace_period: 10s
    
